### ISSUE TITLE
How to build HTML-CSS/SVG output with STIX-Web "fonts"

### ISSUE THREAD

**Issue by jinmincr** [pkra/MathJax-single-file#13]
As the title, I need a compressed mathjax-single-file with STIX-Web "fonts". what should I do?

**Comment by pkra** [comment]
I'm afraid I've not had time to work out an HTML-based output, let alone combining two outputs (curious as to why you'd want that anyway). In any case #9 would come first.

**Comment by pkra** [comment]
Re-reading this, I'm wondering if you meant "either HTML or SVG but with STIX".

**Comment by pkra** [comment]
> Re-reading this, I'm wondering if you meant "either HTML or SVG but with STIX".

To add: I haven't tested it butu it should be easy: replace the `/jax/output/SVG/fonts/TeX/*` references with references to a font other than `TeX` (note that in particular the STIX fonts will have many more files in the respective folder as they provide many more glyphs).

**Comment by pkra** [comment]
SVG output with STIX-web fonts is now possible (and a preconfigured build available); just note #21.

#23 deals with HTML-CSS.
