### ISSUE TITLE
Missing config file error message

### ISSUE THREAD

**Issue by timolawl** [pkra/MathJax-single-file#26]
Hi,

I am getting error messages for not having a configuration file, despite configuring my MathJax properly elsewhere. Using the MathJax single file, I am able to get everything working properly in the following manner:

```
<script src='public/js/MathJax.min.js'>
```

and my configuration in the constructor of a React component:
```
MathJax.Hub.Config({
  jax: ['input/TeX', 'output/AMS_SVG'],
  tex2jax: { inlineMath: [['$', '$'], ['\\(', '\\)']] }
});
```

I have also tried the alternative in placing the configuration as follows, which produces the same results:
```
<script type='text/x-mathjax-config'>
  MathJax.Hub.Config({
    jax: ['input/TeX', 'output/AMS_SVG'],
    tex2jax: { inlineMath: [['$', '$'], ['\\(', '\\)']] }
  });
</script>
<script src='public/js/MathJax.min.js'></script>
```

The single file seeks out a config file in the path: `/jax/output/AMS_SVG/config.js?V=2.7.1`, which produces an error message (in both the left-hand corner of the browser window `File failed to load: /jax/output/AMS_SVG/config.js?V=2.7.1` for brief period of time and in the developer console `Failed to load resource: the server responded with a status of 400 (Bad Request)`). How can I silence this message?

Thank you again for your help,
timolawl

**Comment by pkra** [comment]
Remove the `jax` configuration block; besides `AMS_SVG` being an invalid value, the single-file builds do not allow for configuration that way (all jax components are set at build time and cannot be altered).

**Comment by timolawl** [comment]
Thank you! This solved my problem.

**Comment by pkra** [comment]
Thanks for following up.
