### ISSUE TITLE
Build is not working on Edge

### ISSUE THREAD

**Issue by pkra** [pkra/MathJax-single-file#5]
Cf. https://github.com/readium/readium-js-viewer/issues/394#issuecomment-175788792

A quick test on Edge had the message bar give

`File failed to load: http://192.168.0.161:8080/test/jax/output/HTML-CSS/config.js`

What the?

cc @dpvc if you have any ideas :frowning:

**Comment by pkra** [comment]
test was with the new test file (which unfortunately was committed with MathJax being commented out)

**Comment by pkra** [comment]
Maybe because of https://github.com/pkra/MathJax-single-file/commit/d0271292141d980a412c728bbe47feaa7fdaea64#diff-35b4a816e0441e6a375cd925af50752cL225 ?

**Comment by pkra** [comment]
> Maybe because of d027129#diff-35b4a816e0441e6a375cd925af50752cL225 ?

No, that doesn't change much.

**Comment by dpvc** [comment]
Have you checked whether you have a MathJax cookie that might have HTML-CSS selected in the contextual menu?  Remember that cookies are site-sepecific, so if you had used the menu at some other earlier time on your `http://192.168.0.161:8080` address, that would still be in effect.

**Comment by pkra** [comment]
@dpvc that's not it sadly (fwiw, I usually work in incognito mode). 

I found out today that the un-minified version does not have any problems. So I'll try to update my dependencies and see if it's just a bug in the minifier.

**Comment by pkra** [comment]
@dpvc so I'm confused. I must have made a mistake earlier about the un-minified version doing ok -- or at least I can't reproduce this now.

The problem seems specific to the single-file build on Edge: a) http://s.codepen.io/pkra/debug/QwbJWa renders fine everywhere it should, including Edge, and b) the test in this repo renders fine everywhere except Edge.

Do you have any suggestion on how to debug this? Is there a way to find out what part of the code triggered the load of HTML-CSS's config.js?

**Comment by pkra** [comment]
My goodness, I'm stupid. 

@dpvc as usual, you're correct. It was the cookie after all. Maybe it was also updating the package depdencies; at least it probably won't hurt.

**Comment by danielweck** [comment]
I picked-up your latest changes:
https://github.com/pkra/MathJax-single-file/commit/0b3e56b719b9557064d881376c00eb7eeb54d280

I cleared "everything" in Edge (including cookies)

I still see blank characters in place of MathML:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub-testsuite%2Fmaster%2Fcontent%2F30%2Fepub30-test-0100&goto=%7B%22idref%22%3A%22xhtml-mathml-001%22%7D

**Comment by pkra** [comment]
Thanks, @danielweck. Let's continue on your thread.
