### ISSUE TITLE
MMLSVG: improve configuration

### ISSUE THREAD

**Issue by pkra** [pkra/MathJax-single-file#6]
- menu
  - remove renderer submenu (this build has just one renderer)
  - remove localizations (this build does not include locales)
- remove MathJax notifications
- possible Readium improvements
  - increase Menu z-index (possibly on the fly) to work beyond first page of a chapter
  - turn on zoom
  - add some responsive magic 
    - overflow-x=scroll, responsive line-breaks, or responsive overflow=scale

**Comment by pkra** [comment]
@danielweck do the ideas for Readium sound interesting?

**Comment by pkra** [comment]
Closing this for #24. The Readium suggestions are better done in Readium.

**Comment by danielweck** [comment]
Agreed. The MathJax menu is problematic in very different ways, depending on the view used to layout/render EPUB HTML documents (e.g. reflow paginated vs. scroll).
