### ISSUE TITLE
Include tex extension

### ISSUE THREAD

**Issue by ionelmc** [pkra/MathJax-single-file#7]
I have an usecase where it would be useful to have the tex extension. Is it even possible to bundle it?

**Comment by pkra** [comment]
> Is it even possible to bundle it?

Yes, it shouldn't be hard. Just follow the MathML input components (mml2jax, jax/input/mathml, extensions) and add TeX-related things. I'll try to find the time to test a sample configuration.

**Comment by pkra** [comment]
Check out the texsvg branch for a first attempt of a TeX-input / SVG-output option. I haven't tested it extensively yet.

**Comment by pkra** [comment]
Let's call this resolved by https://github.com/pkra/MathJax-single-file/pull/8
